---
title: "Microbiome 16s & ITS Analysis Report"
author: "Marina LaForgia & Cassie Ettinger"
date: "April 2020"
output: html_document
---

```{r setup, include=FALSE, cache = FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

```

 

```{r Libraries, include = F}
library(EcolUtils)
library(ggplot2)
library(plyr)
library(multcomp)
library(FSA)
library(Rmisc)
library(emmeans)
library(lme4)
library(lmerTest)
library(knitr)
#library(qiimer) not on cran anymore?
library(vegan)
library(ape)
library(Hmisc)
library(phyloseq)
library(RColorBrewer)
library(coin)
library(rmarkdown)
library(reshape)
library(betapart)
library(dada2)
library(extrafont)
library(tidyverse) # for tidy data packages, automatically loads dplyr
library(magrittr) # for piping

## Read in Data ##

# 16S
ps.rare.RA <- readRDS("Data/16S/Intermediates/phyloseq-rare.RDS") # rarefied 16s data
ps.rare.RA <- subset_samples(ps.rare.RA, !(is.na(Competion))) # remove NAs

ps.rare.NC <- readRDS("Data/16S/Intermediates/phyloseq-rare-NC.RDS") # rarefied 16s data without controls
ps.rare.NC <- subset_samples(ps.rare.NC, !(is.na(Competion))) # remove NAs


# Metadata, this file includes biomass 
mapping <- read.csv("/Users/Marina/Documents/UC-Davis/Projects/McL_Nat-Inv-Amplicon/Data/Setup/Grassland-Amplicon-Mapping-File4.csv") 

mapping$FunGroup <- ifelse(mapping$TreatmentName == "Invasive_grass", "Grass", NA)
mapping$FunGroup <- ifelse(mapping$Competion == "SingleSpecies" & mapping$TreatmentName != "Invasive_grass", "Forb", mapping$FunGroup)


```

## 

```{r}

```

## 

```{r}

```


